name: Build Rugby on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable-gnu
    - uses: actions/setup-python@v4.4.0
      with:
        python-version: '3.10'
        architecture: x64
    - name: Build & Run tests
      run: python build.py
